### ISSUE TITLE
File to import not found or unreadable: vendor/breakpoint/breakpoint

### ISSUE THREAD

**Issue by ivalentine** [mmistakes/minimal-mistakes#1606]
- [ ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.11.1
- **Jekyll version:** 3.7.3
- **GitHub Pages hosted:** no
- **Operating system:** macOS El Capitan 10.11.6

---

## Expected behavior

I expected `jekyll build` to build the site.

## Steps to reproduce the behavior

Repo here: https://github.com/ivalentine/ivalentine.net

I updated Jekyll from 3.4.5 to 3.7.3 and Minimal Mistakes from 4.4.2 to 4.11.1. When I ran `jekyll build`, I got this error:

```
  Logging at level: debug
Configuration file: /Users/ian/dev/ivalentine.net/_config.yml
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-feed
         Requiring: jekyll-data
         Requiring: jemoji
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-feed
         Requiring: jemoji
            Source: /Users/ian/dev/ivalentine.net
       Destination: /Users/ian/dev/ivalentine.net/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
           Reading: _projects/sparrow.md
           Reading: _projects/taskdash.md
             Theme: Ignoring assets/css/main.scss in theme due to existing file with that path in site.

           Reading: Theme Data Files...
                    /Users/ian/.rvm/gems/ruby-2.3.4/gems/minimal-mistakes-jekyll-4.11.1/_data/navigation.yml
                    /Users/ian/.rvm/gems/ruby-2.3.4/gems/minimal-mistakes-jekyll-4.11.1/_data/ui-text.yml

           Merging: Theme Data Hash...
                    use --show-data with --verbose to output merged Data Hash.

        Generating: Jekyll::Paginate::Pagination finished in 0.008303 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.002046 seconds.
        Generating: JekyllFeed::Generator finished in 0.001802 seconds.
         Rendering: _projects/sparrow.md
  Pre-Render Hooks: _projects/sparrow.md
  Rendering Liquid: _projects/sparrow.md
  Rendering Markup: _projects/sparrow.md
  Rendering Layout: _projects/sparrow.md
         Rendering: _projects/taskdash.md
  Pre-Render Hooks: _projects/taskdash.md
  Rendering Liquid: _projects/taskdash.md
  Rendering Markup: _projects/taskdash.md
  Rendering Layout: _projects/taskdash.md
         Rendering: _pages/about.md
  Pre-Render Hooks: _pages/about.md
  Rendering Liquid: _pages/about.md
  Rendering Markup: _pages/about.md
  Rendering Layout: _pages/about.md
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
         Rendering: contact/index.md
  Pre-Render Hooks: contact/index.md
  Rendering Liquid: contact/index.md
  Rendering Markup: contact/index.md
  Rendering Layout: contact/index.md
         Rendering: assets/css/main.scss
  Pre-Render Hooks: assets/css/main.scss
  Rendering Liquid: assets/css/main.scss
  Rendering Markup: assets/css/main.scss
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: vendor/breakpoint/breakpoint. Load paths: /Users/ian/dev/ivalentine.net/_sass /Users/ian/.rvm/gems/ruby-2.3.4/gems/minimal-mistakes-jekyll-4.11.1/_sass on line 22
/Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: vendor/breakpoint/breakpoint. (Jekyll::Converters::Scss::SyntaxError)
Load paths:
  /Users/ian/dev/ivalentine.net/_sass
  /Users/ian/.rvm/gems/ruby-2.3.4/gems/minimal-mistakes-jekyll-4.11.1/_sass on line 22
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:98:in `block in convert'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:96:in `each'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:96:in `reduce'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:96:in `convert'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:80:in `render_document'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:62:in `run'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/site.rb:473:in `block in render_pages'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/site.rb:471:in `each'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/site.rb:471:in `render_pages'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/site.rb:191:in `render'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/site.rb:73:in `process'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/ian/.rvm/gems/ruby-2.3.4/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
	from /Users/ian/.rvm/gems/ruby-2.3.4/bin/jekyll:23:in `load'
	from /Users/ian/.rvm/gems/ruby-2.3.4/bin/jekyll:23:in `<main>'
	from /Users/ian/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ian/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

Any help would be appreciated. Thanks very much!

**Comment by mmistakes** [comment]
Your issue is a bunch of the theme's Sass partials are missing. The error above tells you exactly which one... `vendor/breakpoint/breakpoint`.

Looking at your repo you're trying to override some of the theme's Sass partials in `_sass`. Jekyll won't work if you try this. Take a look at the [theme docs](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/) where I explain this.

You either have to copy the entire contents of `_sass` from the theme and adjust as you see fit (sort of defeats the purpose of using the theme as a Ruby gem). For whatever reason Jekyll won't let you override specific Sass partials, it's either all or none.

What you need to do instead is add your variable overrides or any other custom CSS to `/assets/css/main.scss`.

**Comment by ivalentine** [comment]
Thanks so much for the quick response!

I implemented your suggestions, and the issue is now resolved. Much appreciated!
