### ISSUE TITLE
Cannot load such file -- jekyll-sitemap (LoadError)

### ISSUE THREAD

**Issue by sobkowiak** [mmistakes/minimal-mistakes#172]
I have installed `jekyll`and all dependencies like described in http://mmistakes.github.io/minimal-mistakes/theme-setup/. Trying to build or serve the content of this page with `jekyll`I'm getting following  error

```
kso@lenovo:~/work/projects/priv/sobkowiak.github.io.git$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/kso/work/projects/priv/sobkowiak.github.io.git/_config.yml
/var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

This is a list of my gems

```
kso@lenovo:~/work/projects/priv/sobkowiak.github.io.git$ bundle show
Gems included by the bundle:
  * blankslate (2.1.2.4)
  * bundler (1.10.6)
  * celluloid (0.16.0)
  * classifier-reborn (2.0.3)
  * coffee-script (2.3.0)
  * coffee-script-source (1.9.1)
  * colorator (0.1)
  * execjs (2.3.0)
  * fast-stemmer (1.0.2)
  * ffi (1.9.6)
  * hitimes (1.2.2)
  * jekyll (2.5.3)
  * jekyll-coffeescript (1.0.1)
  * jekyll-gist (1.1.0)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (1.3.0)
  * jekyll-sitemap (0.8.0)
  * jekyll-watch (1.2.1)
  * kramdown (1.6.0)
  * liquid (2.6.2)
  * listen (2.8.5)
  * mercenary (0.3.5)
  * octopress (3.0.0.rc.34)
  * octopress-deploy (1.1.0)
  * octopress-escape-code (2.0.6)
  * octopress-hooks (2.6.0)
  * parslet (1.5.0)
  * posix-spawn (0.3.10)
  * pygments.rb (0.6.2)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * redcarpet (3.2.2)
  * safe_yaml (1.0.4)
  * sass (3.4.13)
  * timers (4.0.1)
  * titlecase (0.1.1)
  * toml (0.1.2)
  * yajl-ruby (1.2.1)
```

**Comment by sobkowiak** [comment]
It works using `bundle exec`. Probably problem described [here](https://github.com/mmistakes/minimal-mistakes/issues/98)

**Comment by sobkowiak** [comment]
`bundle update` solved my problem.
