### ISSUE TITLE
Gathered collections results in page build failure due to sitemap.md liquid code

### ISSUE THREAD

**Issue by jenna-jordan** [mmistakes/minimal-mistakes#1799]
## Description

Hi,

Thank you so much for building this theme! I'm really loving it. I'm also new to building a webpage, so please bear with me if this has a seemingly easy fix.

I am trying to gather all of my collections into one directory, as I anticipate creating many collections. I followed the directions in the jekyll documentation [here](https://jekyllrb.com/docs/collections/) for "Gather your collections 3.7.0" and named my collection directory "class_collections" However, when running `bundle exec jekyll serve` I get an error stating: 
```bash
Liquid Exception: undefined method `fetch' for "class_collections":String in sitemap.xml
jekyll 3.7.3 | Error:  undefined method `fetch' for "class_collections":String
```

It also resulted in a GitHub Pages page build failure, though no further description was given from GitHub.

Can this theme simply not handle collection directories yet, or am I implementing it wrong for this theme?

Thanks!!

## Environment

- Minimal Mistakes version: 4.12.1
- Ruby gem or remote theme version: remote theme (forked from minimal-mistakes repo)
- Jekyll version: 3.7.3
- Git repository URL: https://github.com/jenna-jordan/jenna-jordan.github.io
- Operating system: MacOS High Sierra
- GitHub Pages hosted (if yes provide URL to site): https://jenna-jordan.github.io/

---

## Steps to reproduce the behavior

I copy and pasted the output from running `bundle exec jekyll build --trace --verbose`
```bash
bundle exec jekyll build --trace --verbose
  Logging at level: debug
Configuration file: /Users/jenna/Documents/GitHub/jenna-jordan.github.io/_config.yml
      GitHub Pages: github-pages v191
      GitHub Pages: jekyll v3.7.3
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping
         Requiring: jekyll-seo-tag
         Requiring: jekyll-paginate
         Requiring: jekyll-sitemap
         Requiring: jekyll-gist
         Requiring: jekyll-feed
         Requiring: jemoji
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-github-metadata
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: jekyll-remote-theme
   GitHub Metadata: Initializing...
            Source: /Users/jenna/Documents/GitHub/jenna-jordan.github.io
       Destination: /Users/jenna/Documents/GitHub/jenna-jordan.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
      Remote Theme: Downloading https://codeload.github.com/mmistakes/minimal-mistakes/zip/master to /var/folders/qh/hv293wjs439f8w6czngm3xfh0000gn/T/jekyll-remote-theme-20180825-11733-uw16cu.zip
      Remote Theme: Unzipping /var/folders/qh/hv293wjs439f8w6czngm3xfh0000gn/T/jekyll-remote-theme-20180825-11733-uw16cu.zip to /private/var/folders/qh/hv293wjs439f8w6czngm3xfh0000gn/T/jekyll-remote-theme-20180825-11733-cgw2lw
       EntryFilter: excluded /test
       EntryFilter: excluded /docs
       EntryFilter: excluded /README.md
       EntryFilter: excluded /Rakefile
       EntryFilter: excluded /package.json
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /LICENSE.txt
       EntryFilter: excluded /assets/js/plugins
       EntryFilter: excluded /assets/js/vendor
             Theme: Ignoring assets/css/main.scss in theme due to existing file with that path in site.
             Theme: Ignoring assets/js/lunr/lunr-en.js in theme due to existing file with that path in site.
             Theme: Ignoring assets/js/lunr/lunr-gr.js in theme due to existing file with that path in site.
             Theme: Ignoring assets/js/lunr/lunr-store.js in theme due to existing file with that path in site.
             Theme: Ignoring /assets/js/lunr/lunr.js in theme due to existing file with that path in site.
             Theme: Ignoring /assets/js/lunr/lunr.min.js in theme due to existing file with that path in site.
             Theme: Ignoring /assets/js/main.min.js in theme due to existing file with that path in site.
        Generating: JekyllOptionalFrontMatter::Generator finished in 2.9e-05 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 5.3e-05 seconds.
        Generating: JekyllFeed::Generator finished in 0.00055 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.000605 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.001542 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.000355 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 2.4e-05 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.000221 seconds.
         Rendering: _pages/404.md
  Pre-Render Hooks: _pages/404.md
  Rendering Liquid: _pages/404.md
  Rendering Markup: _pages/404.md
  Rendering Layout: _pages/404.md
   GitHub Metadata: Generating for jenna-jordan/jenna-jordan.github.io
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Calling @client.pages("jenna-jordan/jenna-jordan.github.io", {})
         Rendering: _pages/about.md
  Pre-Render Hooks: _pages/about.md
  Rendering Liquid: _pages/about.md
  Rendering Markup: _pages/about.md
  Rendering Layout: _pages/about.md
         Rendering: _pages/blog.md
  Pre-Render Hooks: _pages/blog.md
  Rendering Liquid: _pages/blog.md
  Rendering Markup: _pages/blog.md
  Rendering Layout: _pages/blog.md
         Rendering: _pages/category-archive.md
  Pre-Render Hooks: _pages/category-archive.md
  Rendering Liquid: _pages/category-archive.md
  Rendering Markup: _pages/category-archive.md
  Rendering Layout: _pages/category-archive.md
         Rendering: _pages/class-notes.html
  Pre-Render Hooks: _pages/class-notes.html
  Rendering Liquid: _pages/class-notes.html
  Rendering Markup: _pages/class-notes.html
  Rendering Layout: _pages/class-notes.html
         Rendering: _pages/home.md
  Pre-Render Hooks: _pages/home.md
  Rendering Liquid: _pages/home.md
  Rendering Markup: _pages/home.md
  Rendering Layout: _pages/home.md
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
         Rendering: assets/js/lunr/lunr-en.js
  Pre-Render Hooks: assets/js/lunr/lunr-en.js
  Rendering Liquid: assets/js/lunr/lunr-en.js
  Rendering Markup: assets/js/lunr/lunr-en.js
  Rendering Layout: assets/js/lunr/lunr-en.js
         Rendering: assets/js/lunr/lunr-gr.js
  Pre-Render Hooks: assets/js/lunr/lunr-gr.js
  Rendering Liquid: assets/js/lunr/lunr-gr.js
  Rendering Markup: assets/js/lunr/lunr-gr.js
  Rendering Layout: assets/js/lunr/lunr-gr.js
         Rendering: assets/js/lunr/lunr-store.js
  Pre-Render Hooks: assets/js/lunr/lunr-store.js
  Rendering Liquid: assets/js/lunr/lunr-store.js
  Rendering Markup: assets/js/lunr/lunr-store.js
  Rendering Layout: assets/js/lunr/lunr-store.js
         Rendering: assets/css/main.scss
  Pre-Render Hooks: assets/css/main.scss
  Rendering Liquid: assets/css/main.scss
  Rendering Markup: assets/css/main.scss
         Rendering: _pages/search.md
  Pre-Render Hooks: _pages/search.md
  Rendering Liquid: _pages/search.md
  Rendering Markup: _pages/search.md
  Rendering Layout: _pages/search.md
         Rendering: _pages/sitemap.md
  Pre-Render Hooks: _pages/sitemap.md
  Rendering Liquid: _pages/sitemap.md
  Rendering Markup: _pages/sitemap.md
  Rendering Layout: _pages/sitemap.md
         Rendering: _pages/tag-archive.md
  Pre-Render Hooks: _pages/tag-archive.md
  Rendering Liquid: _pages/tag-archive.md
  Rendering Markup: _pages/tag-archive.md
  Rendering Layout: _pages/tag-archive.md
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
  Rendering Layout: feed.xml
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Liquid Exception: undefined method `fetch' for "class_collections":String in sitemap.xml
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
NoMethodError: undefined method `fetch' for "class_collections":String
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/collection.rb:181:in `write?'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/drops/drop.rb:52:in `public_send'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/drops/drop.rb:52:in `[]'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/context.rb:195:in `lookup_and_evaluate'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable_lookup.rb:38:in `each_index'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable_lookup.rb:38:in `evaluate'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/context.rb:159:in `evaluate'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:106:in `interpret_condition'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:44:in `evaluate'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/filters.rb:245:in `block (2 levels) in where_exp'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/filters.rb:243:in `select'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/filters.rb:243:in `block in where_exp'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/filters.rb:242:in `where_exp'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/strainer.rb:56:in `invoke'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/context.rb:86:in `invoke'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable.rb:78:in `block in render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable.rb:76:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable.rb:76:in `inject'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/variable.rb:76:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/assign.rb:24:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:123:in `render_liquid'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:76:in `render_document'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:62:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:473:in `block in render_pages'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:471:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:471:in `render_pages'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:191:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:73:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
      Remote Theme: Cleaning up /private/var/folders/qh/hv293wjs439f8w6czngm3xfh0000gn/T/jekyll-remote-theme-20180825-11733-cgw2lw
```

**Comment by mmistakes** [comment]
It’s not the theme. Jekyll’s sitemap plug-in doesn’t like something. If you check through the stack trace above it’s throwing errors when it tries to build sitemap.xml

Not sure why it’s having problems with your collections. I have several test collections setup in the theme’s demo site and it compiles fine.

**Comment by mmistakes** [comment]
I think your problem is [this line in your config](
https://github.com/jenna-jordan/jenna-jordan.github.io/blob/master/_config.yml#L284).

I’ve never used `collection_dir` but I’m pretty sure it shouldn’t be indented under the collections key. Try this instead.

```yaml
collections_dir: class_collections
collections:
  is501:
    output: false
    permalink: /:collection/:path/
  is452:
    output: false
    permalink: /:collection/:path/
  is490db:
    output: false
    permalink: /:collection/:path/
  phil103:
    output: false
    permalink: /:collection/:path/
```

If that doesn’t work I’d suggest search through [jekyll/jekyll](
https://github.com/jekyll/jekyll)’s issues. I’ve see problems with the new collection directory feature before. I’m not familiar with it enough to provide help. It’s definitely a core issue and not related to the theme.

**Comment by jenna-jordan** [comment]
Hi,

Thanks for the response! That did fix the page build error. Unfortunately, it also broke my homepage, and github is still throwing an error:

```bash
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
```
Also, when navigating to the test pages they have absolutely no formatting to them.

I think I'm going to try a different method for organizing my pages since it seems there are still some jekyll issues with collection directories.

So to that end, is there a way with the theme to group posts together by tag or category, and also have a main landing page for a specific set of categories/tags?

For example, in my class-notes.html file (using the layout from your test page "post-archive-feature-rows.html"), could I have the url for each button lead to a page or intro post of all posts with a specific tag/category? And then navigate through that categories posts using the custom sidebar menu (one of the primary reasons I chose this theme)?

Also, how do I make the categories and tags on a post visible?

Thanks for your help!!

**Comment by mmistakes** [comment]
If you're hosting with GitHub Pages your options are limited with regards to category and tag pages. You can absolutely add those to your posts, but Jekyll won't be able to automatically create archive pages for those taxonomies (note: categories/tags only work with `_posts` and not collections).

There are plugins that do that, but they're not supported on GitHub Pages. So either you move to a service like Netlify to build/host your site, or you do what the theme's demo pages does and use the category and tag layouts.

See the documentation for more info.

- [Archive settings](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings)
- [Taxonomy archives](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#taxonomy-archives)
