### ISSUE TITLE
ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16 

### ISSUE THREAD

**Issue by fdq09eca** [mmistakes/minimal-mistakes#2444]
the following error occurs every time i have changed during development after I called `bundle exec jekyll serve --livereload`.. Any idea?
```
[2020-03-17 17:30:54] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16 
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-17 17:30:54] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16 
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
[2020-03-17 17:30:54] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
        /Users/macone/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'

```

**Comment by iBug** [comment]
https://github.com/jekyll/jekyll/issues/6899

**Comment by iBug** [comment]
<https://github.com/jekyll/jekyll/issues/6899#issuecomment-382920700>

**Comment by fdq09eca** [comment]
```                    
[2020-03-17 18:55:14] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:17 
        /Users/macone/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `eof?'
        /Users/macone/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `run'
        /Users/macone/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
[2020-03-17 18:55:14] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:25 
        /Users/macone/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `eof?'
        /Users/macone/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/webrick/httpserver.rb:82:in `run'
        /Users/macone/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
```
seems it does not really work..

**Comment by iBug** [comment]
It'd be helpful if you share your `Gemfile.lock` file.

**Comment by fdq09eca** [comment]
```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.2.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.6)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.7)
    faraday (1.0.0)
      multipart-post (>= 1.2, < 3)
    ffi (1.12.2)
    forwardable-extended (2.6.0)
    gemoji (3.0.1)
    html-pipeline (2.12.3)
      activesupport (>= 2)
      nokogiri (>= 1.4)
    http_parser.rb (0.6.0)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    jekyll (3.8.5)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 0.7)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 4)
      safe_yaml (~> 1.0)
    jekyll-feed (0.13.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-gist (1.5.0)
      octokit (~> 4.2)
    jekyll-include-cache (0.2.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (1.5.2)
      sass (~> 3.4)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    jemoji (0.11.1)
      gemoji (~> 3.0)
      html-pipeline (~> 2.2)
      jekyll (>= 3.0, < 5.0)
    kramdown (1.17.0)
    liquid (4.0.3)
    listen (3.2.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.3.6)
    mini_portile2 (2.4.0)
    minimal-mistakes-jekyll (4.19.1)
      jekyll (>= 3.7, < 5.0)
      jekyll-feed (~> 0.1)
      jekyll-gist (~> 1.5)
      jekyll-include-cache (~> 0.1)
      jekyll-paginate (~> 1.1)
      jekyll-sitemap (~> 1.3)
    minitest (5.14.0)
    multipart-post (2.1.1)
    nokogiri (1.10.9)
      mini_portile2 (~> 2.4.0)
    octokit (4.17.0)
      faraday (>= 0.9)
      sawyer (~> 0.8.0, >= 0.5.3)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (3.1.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rouge (3.13.0)
    safe_yaml (1.0.5)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sawyer (0.8.2)
      addressable (>= 2.3.5)
      faraday (> 0.8, < 2.0)
    thread_safe (0.3.6)
    tzinfo (1.2.6)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll
  jekyll-feed
  jekyll-gist
  jekyll-include-cache
  jekyll-paginate
  jekyll-sitemap
  jemoji
  minimal-mistakes-jekyll

BUNDLED WITH
   2.1.4
```
