### ISSUE TITLE
Cannot get two different sites to build using Github Actions

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2489]
I have tried to get https://github.com/lsolesen/cykel-ruter-dk-jekyll and https://github.com/lsolesen/larsolesen-dk-jekyll to build using Github Actions. Both sites builds fine locally and on Travis, but using Github Actions, I get the following error:

Using Jekyll 3.8.5 on https://github.com/lsolesen/cykel-ruter-dk-jekyll:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
jekyll 3.8.5 | Error:  Invalid US-ASCII character "\xE2" on line 54
                    Invalid US-ASCII character "\xE2" on line 54
/usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid US-ASCII character "\\xE2" on line 54 (Jekyll::Converters::Scss::SyntaxError)
```
https://gist.github.com/lsolesen/22d0ef3527888a7dff7471b4f2835317

Using Jekyll 3.8.5 on https://github.com/lsolesen/larsolesen-dk-jekyl

```
2020-04-14T09:13:21.4775572Z �[31m  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':�[0m
2020-04-14T09:13:21.4776122Z jekyll 3.8.5 | Error:  Invalid US-ASCII character "\xE2" on line 54
2020-04-14T09:13:21.4777379Z �[31m                    Invalid US-ASCII character "\xE2" on line 54�[0m
2020-04-14T09:13:21.4778339Z /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid US-ASCII character "\\xE2" on line 54 (Jekyll::Converters::Scss::SyntaxError)
```
https://gist.github.com/lsolesen/74f54fd65dbb2b06abccde5d2e317bbc

And using Jekyll 4.0.0 on https://github.com/lsolesen/larsolesen-dk-jekyl

```
2020-04-14T08:11:22.6750922Z bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
2020-04-14T08:11:22.6751529Z       Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20200414-13818-1wowskd
2020-04-14T08:11:22.6752555Z Encoding::UndefinedConversionError: "\xC3" from ASCII-8BIT to UTF-8
```
https://gist.github.com/lsolesen/084c17e847fed182b591e1e96d0d2a83

The full logs does not really give any hints :(

I have opened an issue https://github.com/jekyll/jekyll/issues/8120 also about it.

**Comment by lsolesen** [comment]
Got it fixed.

**Comment by mmistakes** [comment]
Seems like an environment thing. I've seen countless others report similar errors when using GitLab and Docker to build their sites.

**Comment by aivascu** [comment]
@lsolesen could you provide any details on how you got it fixed? 
I am encountering the same issue when trying to setup the environment on Docker.

**Comment by lsolesen** [comment]
I added --trace to the build command.

**Comment by aivascu** [comment]
@lsolesen thank you, for sharing the solution.
I have [solved](https://github.com/AutoFixture/AutoFixture.github.io/pull/7/files#diff-d41e2ec59f8d1b91106cfb28b42870d5R12) to the issue, by adding environment variables that specified the locale.
The solution was inspired by this [comment](https://github.com/jekyll/jekyll/issues/4268#issuecomment-167406574).
