### ISSUE TITLE
Bumping from 4.17 to 4.20: Could not locate the included file 'read-time.html'

### ISSUE THREAD

**Issue by fayak** [mmistakes/minimal-mistakes#2652]
## Environment

I ran `bundle update`, and when I run `jekyll serve` I encounter the following exception:

```
 Liquid Exception: Could not locate the included file 'read-time.html' in any of ["/srv/jekyll/_includes", "/usr/gem/gems/minimal-mistakes-jekyll-4.20.1/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /usr/gem/gems/minimal-mistakes-jekyll-4.20.1/_layouts/single.html
/usr/gem/gems/jekyll-4.1.1/lib/jekyll/tags/include.rb:223:in `locate_include_file': Could not locate the included file 'read-time.html' in any of ["/srv/jekyll/_includes", "/usr/gem/gems/minimal-mistakes-jekyll-4.20.1/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. (IOError)
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/tags/include.rb:205:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/inclusion.rb:16:in `render'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/tags/include.rb:212:in `block in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/tags/include.rb:210:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/for.rb:160:in `block (2 levels) in render_segment'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `each'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `block in render_segment'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/for.rb:150:in `render_segment'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/for.rb:79:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:127:in `render_liquid'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:190:in `render_layout'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:159:in `place_in_layouts'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:89:in `render_document'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:517:in `block (2 levels) in render_docs'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:516:in `each'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:516:in `block in render_docs'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:515:in `each_value'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:515:in `render_docs'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:207:in `render'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/gem/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:29:in `load'
        from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

It is running under docker, `jekyll/jekyll:latest`

- Minimal Mistakes version: 4.20.1
- Jekyll version: 4.1.1
- Git repository URL: https://github.com/fayak/zarakfr
- Operating system: archlinux, but running under docker

## Expected behavior

No error

## Steps to reproduce the behavior

Go on the 4.17 version (as used on my repo HEAD~2) and run bundle update

**Comment by iBug** [comment]
Check #2526. That file has been renamed. You must have overridden some files which kept some references to the old name.

**Comment by fayak** [comment]
Indeed, my `_includes/archive-single.html` contains a reference to that file ... 

Sorry for the bothering, and thanks for the quick answer !
