### ISSUE TITLE
Error:  undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by blogi-kriptovalyut** [mmistakes/minimal-mistakes#2686]
Hey. I have several sites on the theme for minimal-mistakes.
But one of them doesn't work for updating algolia search index.
I enter the command:

`bundle exec jekyll algolia push`

and I get the error:

```
bundle exec jekyll algolia push
Configuration file: jekyll/name/_config.yml
Processing site...
jekyll 4.1.1 | Error:  undefined method `include?' for nil:NilClass
```

`ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]`

I tried to run bundler and bundle update. It didn't work for me.
I am using plugins:

```
group :jekyll_plugins do
  gem "jekyll-paginate-v2", github: 'mmistakes/jekyll-paginate-v2', :branch => 'jekyll-v4'
  gem "jekyll-archives", "~> 2.1.1"
  gem "jekyll-algolia"
  gem 'jekyll-extlinks'
  gem 'kramdown-parser-gfm'
  gem 'jekyll-loading-lazy'
  gem 'jekyll-multiple-languages-plugin'
end
```

Please tell me where to look for the error?

**Comment by iBug** [comment]
Append `--trace` and examine the output.

**Comment by blogi-kriptovalyut** [comment]
> Append `--trace` and examine the output.
```
jekyll\name>bundle exec jekyll algolia push --trace
Configuration file: D:/GITHUB/jekyll/name/_config.yml
Processing site...
Traceback (most recent call last):
        15: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
        14: from C:/Ruby26-x64/bin/jekyll:23:in `load'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-algolia-1.6.0/lib/jekyll/commands/algolia.rb:31:in `block (2 levels) in init_with_program'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-algolia-1.6.0/lib/jekyll-algolia.rb:82:in `run'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-algolia-1.6.0/lib/jekyll/algolia/overwrites/jekyll-algolia-site.rb:23:in `process'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:180:in `read'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:16:in `read'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:59:in `read_directories'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:74:in `retrieve_posts'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-multiple-languages-plugin-1.7.0/lib/jekyll-multiple-languages-plugin.rb:218:in `read_posts': undefined method `include?' for nil:NilClass (NoMethodError)
```

**Comment by iBug** [comment]
As the stack trace shows, it's something with either `jekyll-algolia` or `jekyll-multiple-languages-plugin`. Examine those plugins for compatibility issues. There's nothing wrong with this theme. Try <https://talk.jekyllrb.com/> instead of here if you need further assistance.

**Comment by blogi-kriptovalyut** [comment]
> As the stack trace shows, it's something with either `jekyll-algolia` or `jekyll-multiple-languages-plugin`. Examine those plugins for compatibility issues. There's nothing wrong with this theme. Try https://talk.jekyllrb.com/ instead of here if you need further assistance.

Oh .. maybe algolia is looking for a `_posts` folder to index. Whereas in `jekyll-multiple-languages-plugin`, the posts are in the `_i18n` folder

**Comment by mmistakes** [comment]
Closing as this is an upstream issue with a plugin this theme has no control over.
