### ISSUE TITLE
Netlify build keeps failing

### ISSUE THREAD

**Issue by velasco** [mmistakes/minimal-mistakes#2716]
Hi there, apologies for the disturbance. Do you have any idea why my netlify build keeps failing?

```
6:50:43 PM: Build ready to start
6:50:44 PM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
6:50:44 PM: build-image tag: v3.4.1
6:50:44 PM: buildbot version: cdc66b02d86506251d3343610a77385376c8c035
6:50:44 PM: Fetching cached dependencies
6:50:44 PM: Failed to fetch cache, continuing with build
6:50:44 PM: Starting to prepare the repo for build
6:50:45 PM: No cached dependencies found. Cloning fresh repo
6:50:45 PM: git clone https://github.com/velasco/momentum-neu
6:50:46 PM: Preparing Git Reference refs/heads/main
6:50:48 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: '_site' versus '_site/' in the Netlify UI
6:50:48 PM: Starting build script
6:50:48 PM: Installing dependencies
6:50:48 PM: Python version set to 2.7
6:50:49 PM: v12.18.0 is already installed.
6:50:50 PM: Now using node v12.18.0 (npm v6.14.4)
6:50:50 PM: Started restoring cached build plugins
6:50:50 PM: Finished restoring cached build plugins
6:50:50 PM: Attempting ruby version 2.7.1, read from environment
6:50:51 PM: Using ruby version 2.7.1
6:50:51 PM: Using bundler version 2.1.4 from Gemfile.lock
6:50:51 PM: Using PHP version 5.6
6:50:51 PM: Started restoring cached ruby gems
6:50:51 PM: Finished restoring cached ruby gems
6:50:51 PM: Installing gem bundle
6:50:52 PM: [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '/opt/build/cache/bundle'`, and stop using this flag
6:50:52 PM: [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`
6:50:54 PM: Fetching gem metadata from https://rubygems.org/..........
6:50:55 PM: Fetching gem metadata from https://rubygems.org/.
6:50:55 PM: Resolving dependencies...
6:50:55 PM: Fetching public_suffix 4.0.6
6:50:55 PM: Installing public_suffix 4.0.6
6:50:55 PM: Fetching addressable 2.7.0
6:50:55 PM: Installing addressable 2.7.0
6:50:55 PM: Using bundler 2.1.4
6:50:55 PM: Fetching colorator 1.1.0
6:50:55 PM: Installing colorator 1.1.0
6:50:55 PM: Fetching concurrent-ruby 1.1.7
6:50:55 PM: Installing concurrent-ruby 1.1.7
6:50:55 PM: Fetching eventmachine 1.2.7
6:50:55 PM: Installing eventmachine 1.2.7 with native extensions
6:51:10 PM: Fetching http_parser.rb 0.6.0
6:51:11 PM: Installing http_parser.rb 0.6.0 with native extensions
6:51:12 PM: Fetching em-websocket 0.5.2
6:51:12 PM: Installing em-websocket 0.5.2
6:51:12 PM: Fetching multipart-post 2.1.1
6:51:12 PM: Installing multipart-post 2.1.1
6:51:12 PM: Fetching ruby2_keywords 0.0.2
6:51:12 PM: Installing ruby2_keywords 0.0.2
6:51:12 PM: Fetching faraday 1.1.0
6:51:12 PM: Installing faraday 1.1.0
6:51:12 PM: Fetching ffi 1.13.1
6:51:12 PM: Installing ffi 1.13.1 with native extensions
6:51:21 PM: Fetching forwardable-extended 2.6.0
6:51:21 PM: Installing forwardable-extended 2.6.0
6:51:21 PM: Fetching i18n 1.8.5
6:51:21 PM: Installing i18n 1.8.5
6:51:21 PM: Fetching sassc 2.4.0
6:51:21 PM: Installing sassc 2.4.0 with native extensions
6:54:04 PM: Fetching jekyll-sass-converter 2.1.0
6:54:04 PM: Installing jekyll-sass-converter 2.1.0
6:54:04 PM: Fetching rb-fsevent 0.10.4
6:54:04 PM: Installing rb-fsevent 0.10.4
6:54:05 PM: Fetching rb-inotify 0.10.1
6:54:05 PM: Installing rb-inotify 0.10.1
6:54:05 PM: Fetching listen 3.2.1
6:54:05 PM: Installing listen 3.2.1
6:54:05 PM: Fetching jekyll-watch 2.2.1
6:54:05 PM: Installing jekyll-watch 2.2.1
6:54:05 PM: Fetching rexml 3.2.4
6:54:05 PM: Installing rexml 3.2.4
6:54:05 PM: Fetching kramdown 2.3.0
6:54:05 PM: Installing kramdown 2.3.0
6:54:05 PM: Fetching kramdown-parser-gfm 1.1.0
6:54:05 PM: Installing kramdown-parser-gfm 1.1.0
6:54:06 PM: Fetching liquid 4.0.3
6:54:06 PM: Installing liquid 4.0.3
6:54:06 PM: Fetching mercenary 0.4.0
6:54:06 PM: Installing mercenary 0.4.0
6:54:06 PM: Fetching pathutil 0.16.2
6:54:06 PM: Installing pathutil 0.16.2
6:54:06 PM: Fetching rouge 3.24.0
6:54:06 PM: Installing rouge 3.24.0
6:54:06 PM: Fetching safe_yaml 1.0.5
6:54:06 PM: Installing safe_yaml 1.0.5
6:54:06 PM: Fetching unicode-display_width 1.7.0
6:54:07 PM: Installing unicode-display_width 1.7.0
6:54:07 PM: Fetching terminal-table 1.8.0
6:54:07 PM: Installing terminal-table 1.8.0
6:54:07 PM: Fetching jekyll 4.1.1
6:54:07 PM: Installing jekyll 4.1.1
6:54:07 PM: Fetching jekyll-feed 0.15.1
6:54:07 PM: Installing jekyll-feed 0.15.1
6:54:07 PM: Fetching sawyer 0.8.2
6:54:07 PM: Installing sawyer 0.8.2
6:54:07 PM: Fetching octokit 4.19.0
6:54:07 PM: Installing octokit 4.19.0
6:54:07 PM: Fetching jekyll-gist 1.5.0
6:54:07 PM: Installing jekyll-gist 1.5.0
6:54:07 PM: Fetching jekyll-include-cache 0.2.1
6:54:08 PM: Installing jekyll-include-cache 0.2.1
6:54:08 PM: Fetching jekyll-paginate 1.1.0
6:54:08 PM: Installing jekyll-paginate 1.1.0
6:54:08 PM: Fetching jekyll-seo-tag 2.7.1
6:54:08 PM: Installing jekyll-seo-tag 2.7.1
6:54:08 PM: Fetching jekyll-sitemap 1.4.0
6:54:08 PM: Installing jekyll-sitemap 1.4.0
6:54:08 PM: Fetching minima 2.5.1
6:54:08 PM: Installing minima 2.5.1
6:54:08 PM: Fetching minimal-mistakes-jekyll 4.20.2
6:54:08 PM: Installing minimal-mistakes-jekyll 4.20.2
6:54:08 PM: Bundle complete! 8 Gemfile dependencies, 41 gems now installed.
6:54:08 PM: Bundled gems are installed into `/opt/build/cache/bundle`
6:54:08 PM: Post-install message from i18n:
6:54:08 PM: HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
6:54:08 PM: But that may break your application.
6:54:08 PM: If you are upgrading your Rails application from an older version of Rails:
6:54:08 PM: Please check your Rails app for 'config.i18n.fallbacks = true'.
6:54:08 PM: If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be'config.i18n.fallbacks = [I18n.default_locale]'.
6:54:08 PM: If not, fallbacks will be broken in your app by I18n 1.1.x.
6:54:08 PM: If you are starting a NEW Rails application, you can ignore this notice.
6:54:08 PM: For more info see:
6:54:08 PM: https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
6:54:08 PM: Gem bundle installed
6:54:08 PM: 5.2 is already installed.
6:54:08 PM: Using Swift version 5.2
6:54:08 PM: Started restoring cached go cache
6:54:08 PM: Finished restoring cached go cache
6:54:08 PM: go version go1.14.4 linux/amd64
6:54:08 PM: go version go1.14.4 linux/amd64
6:54:08 PM: Installing missing commands
6:54:08 PM: Verify run directory
6:54:10 PM: ​
6:54:10 PM: ┌─────────────────────────────┐
6:54:10 PM: │        Netlify Build        │
6:54:10 PM: └─────────────────────────────┘
6:54:10 PM: ​
6:54:10 PM: ❯ Version
6:54:10 PM:   @netlify/build 5.0.3
6:54:10 PM: ​
6:54:10 PM: ❯ Flags
6:54:10 PM:   deployId: 5f985df3b724800008454679
6:54:10 PM:   mode: buildbot
6:54:10 PM: ​
6:54:10 PM: ❯ Current directory
6:54:10 PM:   /opt/build/repo
6:54:10 PM: ​
6:54:10 PM: ❯ Config file
6:54:10 PM:   No config file was defined: using default values.
6:54:10 PM: ​
6:54:10 PM: ❯ Context
6:54:10 PM:   production
6:54:10 PM: ​
6:54:10 PM: ┌───────────────────────────────────┐
6:54:10 PM: │ 1. Build command from Netlify app │
6:54:10 PM: └───────────────────────────────────┘
6:54:10 PM: ​
6:54:10 PM: $ bundle exec jekyll serve
6:54:10 PM: Configuration file: /opt/build/repo/_config.yml
6:54:10 PM:             Source: /opt/build/repo
6:54:10 PM:        Destination: /opt/build/repo/_site
6:54:10 PM:  Incremental build: disabled. Enable with --incremental
6:54:10 PM:       Generating...
6:54:10 PM:        Jekyll Feed: Generating feed for posts
6:54:12 PM:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
6:54:12 PM:                     Error: File to import not found or unreadable: minimal-mistakes/vendor/breakpoint/breakpoint. on line 11:1 of _sass/minimal-mistakes.scss from line 4:1 of main.scss >> @import "minimal-mistakes/vendor/breakpoint/breakpoint"; ^ 
6:54:12 PM:                     ------------------------------------------------
6:54:12 PM:       Jekyll 4.1.1   Please append `--trace` to the `serve` command 
6:54:12 PM:                      for any additional information or backtrace. 
6:54:12 PM:                     ------------------------------------------------
6:54:12 PM: /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:190:in `rescue in convert': Error: File to import not found or unreadable: minimal-mistakes/vendor/breakpoint/breakpoint. (Jekyll::Converters::Scss::SyntaxError)        on line 11:1 of _sass/minimal-mistakes.scss        from line 4:1 of main.scss>> @import "minimal-mistakes/vendor/breakpoint/breakpoint";   ^	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:182:in `convert'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:102:in `block in convert'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `reduce'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `convert'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:84:in `render_document'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:524:in `block in render_pages'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `render_pages'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:208:in `render'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'	from /opt/build/cache/bundle/ruby/2.7.0/bin/jekyll:23:in `load'	from /opt/build/cache/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'	from /opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'	from /opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'/opt/build/repo/_sass/minimal-mistakes.scss:11: Error: File to import not found or unreadable: minimal-mistakes/vendor/breakpoint/breakpoint. (SassC::SyntaxError)
6:54:12 PM:         on line 11:1 of _sass/minimal-mistakes.scss
6:54:12 PM:         from line 4:1 of main.scss
6:54:12 PM: >> @import "minimal-mistakes/vendor/breakpoint/breakpoint";
6:54:12 PM:    ^
6:54:12 PM: 	from /opt/build/cache/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:185:in `convert'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:102:in `block in convert'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `reduce'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `convert'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:84:in `render_document'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:524:in `block in render_pages'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `render_pages'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:208:in `render'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'	from /opt/build/cache/bundle/ruby/2.7.0/bin/jekyll:23:in `load'	from /opt/build/cache/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'	from /opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'	from /opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'​
6:54:12 PM: ┌─────────────────────────────┐
6:54:12 PM: │   "build.command" failed    │
6:54:12 PM: └─────────────────────────────┘
6:54:12 PM: ​
6:54:12 PM:   Error message
6:54:12 PM:   Command failed with exit code 1: bundle exec jekyll serve
6:54:12 PM: ​
6:54:12 PM:   Error location
6:54:12 PM:   In Build command from Netlify app:
6:54:12 PM:   bundle exec jekyll serve
6:54:12 PM: ​
6:54:12 PM:   Resolved config
6:54:12 PM:   build:
6:54:12 PM:     command: bundle exec jekyll serve
6:54:12 PM:     commandOrigin: ui
6:54:12 PM:     publish: /opt/build/repo/_site
6:54:12 PM: Caching artifacts
6:54:12 PM: Started saving ruby gems
6:54:12 PM: Finished saving ruby gems
6:54:12 PM: Started saving build plugins
6:54:12 PM: Finished saving build plugins
6:54:12 PM: Started saving pip cache
6:54:12 PM: Finished saving pip cache
6:54:12 PM: Started saving emacs cask dependencies
6:54:12 PM: Finished saving emacs cask dependencies
6:54:12 PM: Started saving maven dependencies
6:54:12 PM: Finished saving maven dependencies
6:54:12 PM: Started saving boot dependencies
6:54:12 PM: Finished saving boot dependencies
6:54:12 PM: Started saving go dependencies
6:54:12 PM: Finished saving go dependencies
6:54:14 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:54:14 PM: Failing build: Failed to build site
6:54:14 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
6:54:15 PM: Finished processing build request in 3m30.34118266s
```

**Comment by mmistakes** [comment]
What's it doing when you build it locally? I haven't tried to build a site using the theme and Netlify in some time, but this is the line it's erroring on:

```
6:54:12 PM:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
6:54:12 PM:                     Error: File to import not found or unreadable: minimal-mistakes/vendor/breakpoint/breakpoint. on line 11:1 of _sass/minimal-mistakes.scss from line 4:1 of main.scss >> @import "minimal-mistakes/vendor/breakpoint/breakpoint"; ^ 
6:54:12 PM:                     ------------------------------------------------
6:54:12 PM:       Jekyll 4.1.1   Please append `--trace` to the `serve` command 
6:54:12 PM:                      for any additional information or backtrace. 
6:54:12 PM:                     ------------------------------------------------
```

Have you modified the theme at all? Link to a public facing repo would be helpful as I'm just guessing at this point.

**Comment by velasco** [comment]
Building locally works perfectly fine.

**Comment by velasco** [comment]
> What's it doing when you build it locally? I haven't tried to build a site using the theme and Netlify in some time, but this is the line it's erroring on:
> 
> 
> 
> ```
> 
> 6:54:12 PM:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
> 
> 6:54:12 PM:                     Error: File to import not found or unreadable: minimal-mistakes/vendor/breakpoint/breakpoint. on line 11:1 of _sass/minimal-mistakes.scss from line 4:1 of main.scss >> @import "minimal-mistakes/vendor/breakpoint/breakpoint"; ^ 
> 
> 6:54:12 PM:                     ------------------------------------------------
> 
> 6:54:12 PM:       Jekyll 4.1.1   Please append `--trace` to the `serve` command 
> 
> 6:54:12 PM:                      for any additional information or backtrace. 
> 
> 6:54:12 PM:                     ------------------------------------------------
> 
> ```
> 
> 
> 
> Have you modified the theme at all? Link to a public facing repo would be helpful as I'm just guessing at this point.

Ok, no problem. I keep trying. Hoped you have a quick fix. Thanks.

**Comment by mmistakes** [comment]
If it works locally then I'm out of ideas.
