### ISSUE TITLE
Adding defaults for pages throws an error on jekyll serve

### ISSUE THREAD

**Issue by RandomlyKnighted** [mmistakes/minimal-mistakes#312]
I have the following defaults in my _config.yml file:

```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
```

but when I add the lines below to my _config.yml file I get an error.

```
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
```

Here's the error I get when I add the defaults for the pages

```
 Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/single.html
jekyll 3.0.5 | Error:  undefined method `gsub' for nil:NilClass
```

**Comment by mmistakes** [comment]
What does `jekyll serve --trace --verbose` output? That will give you a better idea of what piece of your content (or file) is giving Liquid problems. There's probably a missing piece of YAML Front Matter or something is incompatible with a variable used in `_layouts/single.html` that's blowing it up.

**Comment by RandomlyKnighted** [comment]
Here's the output from the command:

```
jekyll serve --trace --verbose
  Logging at level: debug
Configuration file: C:/projects/randomlyknighted.github.io/_config.yml
     PluginManager: Requiring jekyll-paginate
     PluginManager: Requiring jekyll-sitemap
     PluginManager: Requiring jekyll-gist
     PluginManager: Requiring jekyll-feed
     PluginManager: Requiring jemoji
            Source: C:/projects/randomlyknighted.github.io
       Destination: C:/projects/randomlyknighted.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded /CHANGELOG.md
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /Gruntfile.js
       EntryFilter: excluded /LICENSE
       EntryFilter: excluded /node_modules
       EntryFilter: excluded /package.json
       EntryFilter: excluded /README.md
           Reading: _posts/2015/2015-04-12-welcome.md
           Reading: _posts/2015/2015-04-21-introducing-bower.md
           Reading: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
           Reading: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
           Reading: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
           Reading: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
           Reading: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
           Reading: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
           Reading: _posts/2016/2016-02-07-as-a-new-developer.md
           Reading: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
       EntryFilter: excluded /assets/js/plugins
       EntryFilter: excluded /assets/js/vendor
        Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
         Rendering: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Pre-Render Hooks: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Rendering Liquid: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Rendering Markup: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
         Rendering: _posts/2016/2016-02-07-as-a-new-developer.md
  Pre-Render Hooks: _posts/2016/2016-02-07-as-a-new-developer.md
  Rendering Liquid: _posts/2016/2016-02-07-as-a-new-developer.md
  Rendering Markup: _posts/2016/2016-02-07-as-a-new-developer.md
         Rendering: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Pre-Render Hooks: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Rendering Liquid: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Rendering Markup: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
         Rendering: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Pre-Render Hooks: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Rendering Liquid: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Rendering Markup: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
         Rendering: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Pre-Render Hooks: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Rendering Liquid: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Rendering Markup: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
         Rendering: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Pre-Render Hooks: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Rendering Liquid: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Rendering Markup: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
         Rendering: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Pre-Render Hooks: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Rendering Liquid: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Rendering Markup: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
         Rendering: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Pre-Render Hooks: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Rendering Liquid: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Rendering Markup: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
         Rendering: _posts/2015/2015-04-21-introducing-bower.md
  Pre-Render Hooks: _posts/2015/2015-04-21-introducing-bower.md
  Rendering Liquid: _posts/2015/2015-04-21-introducing-bower.md
  Rendering Markup: _posts/2015/2015-04-21-introducing-bower.md
         Rendering: _posts/2015/2015-04-12-welcome.md
  Pre-Render Hooks: _posts/2015/2015-04-12-welcome.md
  Rendering Liquid: _posts/2015/2015-04-12-welcome.md
  Rendering Markup: _posts/2015/2015-04-12-welcome.md
  Rendering Markup: sitemap.xml
 Post-Render Hooks: sitemap.xml
         Rendering: _posts/2015/2015-04-12-welcome.md
  Pre-Render Hooks: _posts/2015/2015-04-12-welcome.md
  Rendering Liquid: _posts/2015/2015-04-12-welcome.md
  Rendering Markup: _posts/2015/2015-04-12-welcome.md
  Rendering Layout: _posts/2015/2015-04-12-welcome.md
         Rendering: _posts/2015/2015-04-21-introducing-bower.md
  Pre-Render Hooks: _posts/2015/2015-04-21-introducing-bower.md
  Rendering Liquid: _posts/2015/2015-04-21-introducing-bower.md
  Rendering Markup: _posts/2015/2015-04-21-introducing-bower.md
  Rendering Layout: _posts/2015/2015-04-21-introducing-bower.md
         Rendering: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Pre-Render Hooks: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Rendering Liquid: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Rendering Markup: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
  Rendering Layout: _posts/2015/2015-05-06-installing-a-nuget-package-programmatically.md
         Rendering: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Pre-Render Hooks: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Rendering Liquid: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Rendering Markup: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
  Rendering Layout: _posts/2015/2015-05-21-grunt,-a-javascript-task-runner.md
         Rendering: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Pre-Render Hooks: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Rendering Liquid: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Rendering Markup: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
  Rendering Layout: _posts/2015/2015-06-07-an-article-from-msdn-magazine-on-sidewaffle.md
         Rendering: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Pre-Render Hooks: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Rendering Liquid: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Rendering Markup: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
  Rendering Layout: _posts/2015/2015-08-21-welcome-to-microsoft-azure.md
         Rendering: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Pre-Render Hooks: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Rendering Liquid: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Rendering Markup: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
  Rendering Layout: _posts/2015/2015-10-18-gulpjs,-another-javascript-task-runner.md
         Rendering: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Pre-Render Hooks: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Rendering Liquid: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Rendering Markup: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
  Rendering Layout: _posts/2015/2015-11-06-why-you-should-avoid-gethashcode.md
         Rendering: _posts/2016/2016-02-07-as-a-new-developer.md
  Pre-Render Hooks: _posts/2016/2016-02-07-as-a-new-developer.md
  Rendering Liquid: _posts/2016/2016-02-07-as-a-new-developer.md
  Rendering Markup: _posts/2016/2016-02-07-as-a-new-developer.md
  Rendering Layout: _posts/2016/2016-02-07-as-a-new-developer.md
         Rendering: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Pre-Render Hooks: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Rendering Liquid: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Rendering Markup: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
  Rendering Layout: _posts/2016/2016-04-10-object-oriented-javascript-for-csharp-developers-part-one.md
         Rendering: /_pages/404.md
  Pre-Render Hooks: /_pages/404.md
  Rendering Liquid: /_pages/404.md
  Rendering Markup: /_pages/404.md
  Rendering Layout: _pages/404.md
  Rendering Layout: _pages/404.md
  Rendering Layout: _pages/404.md
 Post-Render Hooks: /_pages/404.md
         Rendering: atom.xml
  Pre-Render Hooks: atom.xml
  Rendering Liquid: atom.xml
  Rendering Markup: atom.xml
  Rendering Layout: atom.xml
  Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/single.html
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/base.rb:98:in `adapt_source': undefined method `gsub' for nil:NilClass (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/kramdown.rb:89:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/gfm.rb:29:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/base.rb:69:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/document.rb:107:in `initialize'

        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/converters/markdown/kramdown_parser.rb:28:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/converters/markdown/kramdown_parser.rb:28:in `convert'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/converters/markdown.rb:60:in `convert'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/filters.rb:15:in `markdownify'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/strainer.rb:51:in `invoke'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/context.rb:95:in `invoke'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/variable.rb:88:in `block in render'

        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/variable.rb:86:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/variable.rb:86:in `inject'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/variable.rb:86:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/tags/unless.rb:15:in `block in render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/tags/unless.rb:10:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'

        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/convertible.rb:112:in `render_liquid'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/convertible.rb:215:in `render_all_layouts'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/convertible.rb:263:in `do_layout'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/page.rb:116:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:179:in `block in render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:177:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:177:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:59:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/commands/build.rb:60:in `build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/commands/build.rb:35:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/bin/jekyll:17:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'
```

**Comment by mmistakes** [comment]
Hmm nothing is sticking out to me. It sure looks like it's your content though. I'd start by moving all of your posts and pages, build, see if that works. Then move a few back at a time to identify the problem child.

It looks like the error happens right around when the `jekyll-feed` is doing its thing to build the `atom.xml` file. And then throws some Kramdown parsing errors. This all seems to point to something in your content the Markdown converter doesn't like.

```
Rendering Layout: atom.xml
  Liquid Exception: undefined method `gsub' for nil:NilClass in _layouts/single.html
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/base.rb:98:in `adapt_source': undefined method `gsub' for nil:NilClass (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/kramdown.rb:89:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/gfm.rb:29:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/parser/base.rb:69:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib/kramdown/document.rb:107:in `initialize'
```

I'm far from a Jekyll expert so you might want to search some closed issues in the Jekyll repo or the [Jekyll Talk forums](https://talk.jekyllrb.com/t/liquid-exception-undefined-method-gsub-for-nil-nilclass-in--includes-head-html-included-in--layouts-default-html/1911/8). I know I've seen similar errors like this before, just can't place where.

And stupid question but are your running Jekyll with `bundle exec jekyll serve` and `bundle exec jekyll build`? If not I would start. It's likely a gem conflict and running with Bundler fixes most of this Ruby environment issues.

**Comment by RandomlyKnighted** [comment]
I installed bundler and ran `bundle install`. I was missing a few things so I tried serving the files again but still got the error. Next I removed all the files under `_posts` and tried again. Once again I got the same error so I reran `jekyll serve --trace --verbose` and got the following error message:

```
jekyll serve --trace --verbose
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
  Logging at level: debug
Configuration file: C:/projects/randomlyknighted.github.io/_config.yml
     PluginManager: Requiring jekyll-paginate
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-paginate (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:27:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:27:in `require_gems'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:97:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/site.rb:49:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/commands/build.rb:30:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/commands/build.rb:30:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.5/bin/jekyll:17:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'
````

This time it looks like the issue is with `jekyll-paginate`.

**Comment by mmistakes** [comment]
Not sure then. Looks like plugin related stuff. And since I didn't write
the plugins I'm out of ideas.

**Comment by andreabedini** [comment]
I am experiencing the same problem as @RandomlyKnighted. Almost identical [stack trace](https://gist.github.com/andreabedini/4eb23d337d5d06edf034fbf93383b7fe) only minor versions differs. What puzzles me is that `test.md` is just

```
---
layout: single
---

test
```

**Comment by mmistakes** [comment]
I'm 99.9% sure this is related to both of your Ruby environments, especially in your case @andreabedini, since you appear to only have added 1 test file.

I know I've experienced the same thing at some point and it took getting the right mix of versions in the `Gemfile` and `bundle exec jekyll serve` to solve it.

As suggested before I'd start searching [Jekyll's issues](https://github.com/jekyll/jekyll/issues) and the [Jekyll Talk forums](https://talk.jekyllrb.com/) because I know I've seen this exact same error talked about.

Another suggestion would be to update the dependencies with `bundle update` then try `bundle exec jekyll serve` again and see what happens.

And since it seems like it `jekyll-paginate` or `jekyll-feed` might be a potential problem for you deactivate them to verify.

1. Remove `index.html` temporarily since it invokes pagination and will through an error if you try a build with it turned off.
2. Go into `_config.yml` and comment out the Jekyll plugins.
```yaml
    gems:
      # - jekyll-paginate
      # - jekyll-sitemap
      # - jekyll-gist
      # - jekyll-feed
      # - jemoji
```
3. Run `bundle exec jekyll serve` and see if the stopped the errors.

**Comment by mmistakes** [comment]
Possibly related issue #261

**Comment by mmistakes** [comment]
Also @andreabedini I just ran the same `test.md`

```yaml
---
layout: single
---

Test
```

And got the exact same error as you. You're missing `title:` in the YAML. For pages you'll need that or else it will break things. Posts you do not since Jekyll pulls it from the file name eg: `2016-05-10-your-awesome-post.md`, but pages don't have that behavior.

So do this instead for a page:

```yaml
---
title: "Your Post Title"
layout: single
---

Test
```

**Comment by andreabedini** [comment]
thanks @mmistakes, I just reached the same conclusion. Adding a title solved my problem.

**Comment by RandomlyKnighted** [comment]
I don't think I had a title on my home page so I'll try that out when I get home tonight and will let you know how it goes.

**Comment by mmistakes** [comment]
Home page doesn't need it. It would just be for any pages you use the `single` layout.

**Comment by RandomlyKnighted** [comment]
Ok well I was able to get your gh-pages branch to run finally. Though I had to make a change or two. With the latest version of Ruby you have to add `gem "nokogiri", "~> 1.6.8.rc2"` to your gemfile otherwise `bundle update` will fail. 

I've run the `build:all` npm script and the `bundle exec jekyll serve` but when the page loads it's like there's no CSS on the page at all. Am I missing something?

**Comment by mmistakes** [comment]
1. Verify `_site/assets/CSS/main.css` exists and has all the styles. 
2. View source of a page and see what the path is for the CSS. That will be a big clue on what is going on and if it's pointing to the wrong location. 
3. Verify you set `url` in _config.yml properly. If it has your production domain and you're previewing locally it's going to be missing. Be sure it's `url: http://localhost:4000` or blank in that case.

**Comment by flohw** [comment]
I had the same problem here and solved it by the same way. (adding `title` in the YAML)
Is it possible to set the title value inside the defaults section as it would be by default ? Something like this :
```yaml
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      title: # something here to match the default behavior
```

**Comment by mmistakes** [comment]
@flohw I don't think that would work since you probably wouldn't want every page to have the same title. You could get more specific with `path` but at that point you're essentially doing the same thing as putting a `title` in the page's YAML.

**Comment by RandomlyKnighted** [comment]
@mmistakes I'll be able to follow up on your CSS recommendations this afternoon.

**Comment by mmistakes** [comment]
@flohw Also for what it's worth, as a best practice you should be setting a `title` for every page anyways. I could certainly make `page.title` conditional and that would eliminate the error, but then you end up with no `<title>` elements on those pages. Which is generally a really bad thing for SEO.

If you look at what the Jekyll does with `jekyll new my-awesome-site` it's creating an About page and includes `title: About` in the YAML Front Matter. So this isn't something out of the norm. I think the fact that posts autogenerate a title and pages don't is where people get tripped up.

**Comment by flohw** [comment]
@mmistakes Ok, I understand that point. I though that Jekyll creates also a title for pages.
I started to use Jekyll few days ago :-)

**Comment by interactivetech** [comment]
I was facing this issue, and what recently helped me was changing the Gem file, specified in https://github.com/mmistakes/minimal-mistakes/issues/2379#issuecomment-578132809 
and running `bundle install`
