### ISSUE TITLE
Liquid Exception: divided by 0 error

### ISSUE THREAD

**Issue by QuantLab** [mmistakes/minimal-mistakes#317]
Hey Mike,
If my post becomes quite big I get an error `Liquid Exception: divided by 0 in _includes/archive-single.html, included in _layouts/single.html`

What may cause this behavior?

**Comment by mmistakes** [comment]
Not sure. Might just be a Jekyll problem (or bug) and not something directly related to the theme. Do you have a public repo with the problem post that I could look at and potentially troubleshoot?

Running Jekyll with `bundle exec jekyll --verbose --trace` might give you some more clues on what Jekyll is having problems with. Could also be something in your content (bad YAML variable, lack of YAML, etc).

**Comment by QuantLab** [comment]
I get following output after `bundle exec jekyll build --trace`:

```
Liquid Exception: divided by 0 in _includes/archive-single.html, included in _layouts/single.html
~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/tags/include.rb:133:in `rescue in render': divided by 0 (Jekyll::Tags::IncludeTagError)
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/tags/include.rb:125:in `render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/for.rb:113:in `block (2 levels) in render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each_with_index'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `block in render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/for.rb:99:in `render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:39:in `block (2 levels) in render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `block in render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/tags/if.rb:36:in `render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/renderer.rb:105:in `render_liquid'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/renderer.rb:147:in `place_in_layouts'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/renderer.rb:69:in `run'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:171:in `block (2 levels) in render'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:169:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:169:in `block in render'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:168:in `each'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:168:in `render'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:59:in `process'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/command.rb:28:in `process_site'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:60:in `build'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:35:in `process'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/bin/jekyll:23:in `load'
from ~/minimal-mistakes/vendor/bundle/ruby/2.0.0/bin/jekyll:23:in `<main>'
```

**Comment by mmistakes** [comment]
What about a public repo and the page/post causing the problem? This looks
content related and not necessarily theme related.

**Comment by QuantLab** [comment]
So far I experiment locally. 
But it is a usual markdown file with simple text in _posts directory, adding more text cause this error. 
For example I have post that is working well giving error when I add the same copypasted text i.e. overall text is doubled.

**Comment by mmistakes** [comment]
Not sure what you're doing but you're missing something that's for sure. There's likely a bit of Markdown or missing YAML that's causing your problem. But without having the files you're using there is absolutely no way I can reproduce.

If you can put it up on GitHub, share it zipped up on Dropbox, or put in Gists I really can't help.

**Comment by QuantLab** [comment]
> But without having the files you're using there is absolutely no way I can reproduce. If you can put it up on GitHub, share it zipped up on Dropbox, or put in Gists I really can't help. 

Ok, maybe later if I still wouldn't be able to figure it out.
Thanks for help ;-)

**Comment by Scot3004** [comment]
Have you defined the parameter "words_per_minute" in _config.yml and your post is not configured to show read_time, in the include read_time.html, this could throw the exception

**Comment by mmistakes** [comment]
Thanks @Scot3004 for identifying the cause of the error and fixing it with the PR. I appreciate it!
