### ISSUE TITLE
jekyll 3.9.2 | Error:  incomplete "\x00" on UTF-16LE in /_layouts/default.html

### ISSUE THREAD

**Issue by silvio2402** [mmistakes/minimal-mistakes#3831]
### What happened?

- Minimal Mistakes version: I'm using `remote_theme` (so latest?)
- Ruby gem or remote theme version: gem 3.3.7
- Jekyll version: jekyll 3.9.2
- Git repository URL: [silvio2402/silviobraendle.ch](https://github.com/silvio2402/silviobraendle.ch)
- Hosted on GitHub Pages (if yes provide URL to site): [silviobraendle.ch](https://silviobraendle.ch)
- Operating system: Windows 11 21H2 22000.795

I'm getting this error when running `bundle exec jekyll serve`:
```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Configuration file: C:/Users/silvi/Projects/silviobraendle-ch/_config.yml
            Source: C:/Users/silvi/Projects/silviobraendle-ch
       Destination: C:/Users/silvi/Projects/silviobraendle-ch/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme mmistakes/minimal-mistakes
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
  Liquid Exception: incomplete "\x00" on UTF-16LE in /_layouts/default.html
jekyll 3.9.2 | Error:  incomplete "\x00" on UTF-16LE
C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:652:in `encode': incomplete "\\x00" on UTF-16LE (Encoding::InvalidByteSequenceError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:652:in `read'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:54:in `read_s'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:106:in `block (5 levels) in get_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:104:in `each'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:104:in `find'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:104:in `block (4 levels) in get_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:435:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:542:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:103:in `block (3 levels) in get_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:612:in `each_key'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:102:in `block (2 levels) in get_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:435:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:542:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:101:in `block in get_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:435:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/registry.rb:542:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:78:in `get_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/win32/resolv.rb:21:in `get_resolv_info'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:994:in `default_config_hash'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:1011:in `block in lazy_initialize'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:1004:in `synchronize'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:1004:in `lazy_initialize'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:353:in `block in lazy_initialize'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:351:in `synchronize'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:351:in `lazy_initialize'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:513:in `fetch_resource'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:507:in `each_resource'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:402:in `each_address'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:378:in `getaddress'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/client.rb:111:in `block in internet_connected?'
        from C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:298:in `open'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/client.rb:109:in `internet_connected?'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/client.rb:81:in `save_from_errors'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/client.rb:63:in `method_missing'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/repository.rb:56:in `block in repo_pages_info'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/value.rb:55:in `call_or_value'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/value.rb:29:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/repository.rb:56:in `repo_pages_info'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-github-metadata-2.13.0/lib/jekyll-github-metadata/repository.rb:181:in `html_url'
        from C:/Ruby31-x64/lib/ruby/3.1.0/forwardable.rb:238:in `url'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/drops/drop.rb:52:in `public_send'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/drops/drop.rb:52:in `[]'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:197:in `lookup_and_evaluate'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `each_index'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `evaluate'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:159:in `evaluate'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:112:in `block in evaluate_filter_expressions'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:112:in `map'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:112:in `evaluate_filter_expressions'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:83:in `block in render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/tags/include.rb:140:in `block in render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/tags/include.rb:137:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/tags/include.rb:140:in `block in render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/tags/include.rb:137:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:126:in `render_liquid'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:195:in `render_layout'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:158:in `place_in_layouts'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:88:in `render_document'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `block in render_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `each_value'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `render_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:191:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby31-x64/bin/jekyll:32:in `load'
        from C:/Ruby31-x64/bin/jekyll:32:in `<main>'
```

What's weird is that the error doesn't occur with the GitHub Actions Workflow.
Serving the site locally always used to work until I re-ran the jekyll serve command.

I have tried:
- Restarting the computer
- Re-cloning my repo
- Completely uninstalling and reinstalling Ruby
- Cloning the [mmistakes/mm-github-pages-starter](https://github.com/mmistakes/mm-github-pages-starter) repo, running `bundle`, then `bundle exec jekyll serve` and got the same error

### Expected behavior

I expect the site to be built and served.

### Steps to reproduce the behavior

1. Clone and go in the starter repo:
```bash
git clone https://github.com/mmistakes/mm-github-pages-starter.git
cd mm-github-pages-starter
```
2. Run `bundle`:
```bash
bundle
```
3. Run `bundle exec jekyll serve`
```bash
bundle exec jekyll serve
```

### Other

Please leave me any thoughts and clues to why this might be happening.
Thanks in advance!

**Comment by silvio2402** [comment]
Hi @iBug, thanks for your reply.
I already looked up the GitHub metadata warning and found this

**Comment by silvio2402** [comment]
Oops, I didn’t mean to close it

**Comment by silvio2402** [comment]
I got the local server to work through [WSL](https://docs.microsoft.com/en-us/windows/wsl/).
