### ISSUE TITLE
Missing gems (path issue?)

### ISSUE THREAD

**Issue by namebrandon** [mmistakes/minimal-mistakes#87]
**resolved** - rbenv rehash..

sorry for the silly issue request, just took an hour of googling, but it's up and running.

---

Just getting started here with Jekyll / Ruby, so I'm very sure this is a mistake on my part, perhaps with some environment variable Ruby may depend on (or a virtual environment?). I had used this box before for testing out Ruby, though I did run through the 'apt-get install' steps anyway, just to be sure I wasn't missing anything.

I didn't paste the output of the bundle install or other install commands, they all executed fine, no errors there. 

I'd appreciate any suggestions!

```
brandon@ruby:~/jekyll/minimal-mistakes$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
brandon@ruby:~/jekyll/minimal-mistakes$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

```
brandon@ruby:~/jekyll$ git clone https://github.com/mmistakes/minimal-mistakes.git

brandon@ruby:~/jekyll$ cd minimal-mistakes/

brandon@ruby:~/jekyll/minimal-mistakes$ gem install bundler

brandon@ruby:~/jekyll/minimal-mistakes$ bundle install

brandon@ruby:~/jekyll/minimal-mistakes$ jekyll serve --watch
Configuration file: /home/brandon/jekyll/minimal-mistakes/_config.yml
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- jekyll-sitemap (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `block in require_gems'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `each'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `require_gems'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
    from /var/lib/gems/1.9.1/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'
brandon@ruby:~/jekyll/minimal-mistakes$ gem show sass
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command show


brandon@ruby:~/jekyll/minimal-mistakes$ bundle show sass
/home/brandon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-3.4.5
```

Just found about this command, so pasting as I assume it's relevant..

```
brandon@ruby:~/jekyll/minimal-mistakes$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.2 (2014-05-08 patchlevel 95) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/brandon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
  - RUBY EXECUTABLE: /home/brandon/.rbenv/versions/2.1.2/bin/ruby
  - EXECUTABLE DIRECTORY: /home/brandon/.rbenv/versions/2.1.2/bin
  - SPEC CACHE DIRECTORY: /home/brandon/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/brandon/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
     - /home/brandon/.gem/ruby/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/brandon/.rbenv/versions/2.1.2/bin
     - /home/brandon/.rbenv/libexec
     - /home/brandon/.rbenv/plugins/ruby-build/bin
     - /home/brandon/.rbenv/plugins/ruby-build/bin
     - /home/brandon/.rbenv/shims
     - /home/brandon/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /home/brandon/.rbenv/versions/2.1.2/bin
```

**Comment by pagalsurd** [comment]
On Windows, `bundle check` and then `bundle update` resolved the issue for me.
